packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@eslint/eslintrc': '^3.3.3'
  '@eslint/js': '^9.39.2'
  'eslint': '^9.39.2'
  'prettier': '^3.4.2'
  'rimraf': '^6.0.1'
  'typescript': '^5.9.3'

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - bcrypt
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver
